// Mocks generated by Mockito 5.4.6 from annotations
// in neotradingbotback1777/test/presentation/grpc/trading_service_grpc_backtest_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:decimal/decimal.dart' as _i7;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:neotradingbotback1777/application/use_cases/run_backtest_use_case.dart'
    as _i3;
import 'package:neotradingbotback1777/domain/entities/app_settings.dart' as _i8;
import 'package:neotradingbotback1777/domain/failures/failures.dart' as _i6;
import 'package:neotradingbotback1777/domain/services/i_trading_api_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeITradingApiService_0 extends _i1.SmartFake
    implements _i2.ITradingApiService {
  _FakeITradingApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RunBacktestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunBacktestUseCase extends _i1.Mock
    implements _i3.RunBacktestUseCase {
  MockRunBacktestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITradingApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeITradingApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ITradingApiService);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i3.BacktestResult>> call({
    required String? symbol,
    required int? startTime,
    required int? endTime,
    required String? interval,
    required _i7.Decimal? initialBalance,
    required _i8.AppSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #symbol: symbol,
            #startTime: startTime,
            #endTime: endTime,
            #interval: interval,
            #initialBalance: initialBalance,
            #settings: settings,
          },
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i3.BacktestResult>>.value(
                _i9.dummyValue<_i5.Either<_i6.Failure, _i3.BacktestResult>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #symbol: symbol,
              #startTime: startTime,
              #endTime: endTime,
              #interval: interval,
              #initialBalance: initialBalance,
              #settings: settings,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i3.BacktestResult>>);
}
