// Mocks generated by Mockito 5.4.6 from annotations
// in neotradingbotback1777/test/infrastructure/persistence/hive/strategy_state_repository_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:neotradingbotback1777/domain/entities/account_info.dart' as _i8;
import 'package:neotradingbotback1777/domain/entities/exchange_info.dart'
    as _i11;
import 'package:neotradingbotback1777/domain/entities/kline.dart' as _i12;
import 'package:neotradingbotback1777/domain/entities/order_response.dart'
    as _i6;
import 'package:neotradingbotback1777/domain/entities/price.dart' as _i10;
import 'package:neotradingbotback1777/domain/entities/ticker_info.dart' as _i9;
import 'package:neotradingbotback1777/domain/failures/failures.dart' as _i5;
import 'package:neotradingbotback1777/domain/services/i_trading_api_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ITradingApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITradingApiService extends _i1.Mock
    implements _i2.ITradingApiService {
  MockITradingApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTestMode => (super.noSuchMethod(
        Invocation.getter(#isTestMode),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.OrderResponse>> createOrder({
    required String? symbol,
    required double? quantity,
    required String? side,
    String? clientOrderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #symbol: symbol,
            #quantity: quantity,
            #side: side,
            #clientOrderId: clientOrderId,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.OrderResponse>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.OrderResponse>>(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #symbol: symbol,
              #quantity: quantity,
              #side: side,
              #clientOrderId: clientOrderId,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.OrderResponse>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.AccountInfo>> getAccountInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i8.AccountInfo>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i8.AccountInfo>>(
          this,
          Invocation.method(
            #getAccountInfo,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i8.AccountInfo>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>> getOpenOrders(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOpenOrders,
          [symbol],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>(
          this,
          Invocation.method(
            #getOpenOrders,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, double>> subscribeToPriceStream(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPriceStream,
          [symbol],
        ),
        returnValue: _i3.Stream<_i4.Either<_i5.Failure, double>>.empty(),
      ) as _i3.Stream<_i4.Either<_i5.Failure, double>>);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, _i8.AccountInfo>>
      subscribeToAccountInfoStream() => (super.noSuchMethod(
            Invocation.method(
              #subscribeToAccountInfoStream,
              [],
            ),
            returnValue:
                _i3.Stream<_i4.Either<_i5.Failure, _i8.AccountInfo>>.empty(),
          ) as _i3.Stream<_i4.Either<_i5.Failure, _i8.AccountInfo>>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getWebSocketStats() => (super.noSuchMethod(
        Invocation.method(
          #getWebSocketStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> forceWebSocketReconnect() => (super.noSuchMethod(
        Invocation.method(
          #forceWebSocketReconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.TickerInfo>> getTickerInfo(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTickerInfo,
          [symbol],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i9.TickerInfo>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i9.TickerInfo>>(
          this,
          Invocation.method(
            #getTickerInfo,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i9.TickerInfo>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i10.Price>> getLatestPrice(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestPrice,
          [symbol],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i10.Price>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i10.Price>>(
          this,
          Invocation.method(
            #getLatestPrice,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i10.Price>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i11.ExchangeInfo>> getExchangeInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExchangeInfo,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i11.ExchangeInfo>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i11.ExchangeInfo>>(
          this,
          Invocation.method(
            #getExchangeInfo,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i11.ExchangeInfo>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure,
          List<Map<String, dynamic>>>> getAccountTradeFees() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountTradeFees,
          [],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>(
          this,
          Invocation.method(
            #getAccountTradeFees,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<String>>> getActiveSymbols() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSymbols,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<String>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<String>>>(
          this,
          Invocation.method(
            #getActiveSymbols,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> cancelOrder({
    required String? symbol,
    required int? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [],
          {
            #symbol: symbol,
            #orderId: orderId,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #cancelOrder,
            [],
            {
              #symbol: symbol,
              #orderId: orderId,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> cancelAllOpenOrders(
          {required String? symbol}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAllOpenOrders,
          [],
          {#symbol: symbol},
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #cancelAllOpenOrders,
            [],
            {#symbol: symbol},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  void updateMode({required bool? isTestMode}) => super.noSuchMethod(
        Invocation.method(
          #updateMode,
          [],
          {#isTestMode: isTestMode},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i12.Kline>>> getKlines({
    required String? symbol,
    required String? interval,
    int? startTime,
    int? endTime,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKlines,
          [],
          {
            #symbol: symbol,
            #interval: interval,
            #startTime: startTime,
            #endTime: endTime,
            #limit: limit,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, List<_i12.Kline>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i12.Kline>>>(
          this,
          Invocation.method(
            #getKlines,
            [],
            {
              #symbol: symbol,
              #interval: interval,
              #startTime: startTime,
              #endTime: endTime,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i12.Kline>>>);
}
