// Mocks generated by Mockito 5.4.6 from annotations
// in neotradingbotback1777/test/application/use_cases/start_trading_loop_atomic_race_condition_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:neotradingbotback1777/application/managers/atomic_state_manager.dart'
    as _i16;
import 'package:neotradingbotback1777/domain/entities/account_info.dart'
    as _i13;
import 'package:neotradingbotback1777/domain/entities/app_settings.dart'
    as _i11;
import 'package:neotradingbotback1777/domain/entities/app_strategy_state.dart'
    as _i2;
import 'package:neotradingbotback1777/domain/entities/price.dart' as _i9;
import 'package:neotradingbotback1777/domain/entities/symbol_info.dart' as _i15;
import 'package:neotradingbotback1777/domain/entities/ticker_info.dart' as _i8;
import 'package:neotradingbotback1777/domain/failures/failures.dart' as _i6;
import 'package:neotradingbotback1777/domain/repositories/account_repository.dart'
    as _i12;
import 'package:neotradingbotback1777/domain/repositories/i_symbol_info_repository.dart'
    as _i14;
import 'package:neotradingbotback1777/domain/repositories/price_repository.dart'
    as _i3;
import 'package:neotradingbotback1777/domain/services/trade_evaluator_service.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppStrategyState_0 extends _i1.SmartFake
    implements _i2.AppStrategyState {
  _FakeAppStrategyState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PriceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPriceRepository extends _i1.Mock implements _i3.PriceRepository {
  MockPriceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> saveCurrentPrice(
    String? symbol,
    double? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCurrentPrice,
          [
            symbol,
            price,
          ],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #saveCurrentPrice,
            [
              symbol,
              price,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, double?>> getCurrentPrice(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPrice,
          [symbol],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, double?>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, double?>>(
          this,
          Invocation.method(
            #getCurrentPrice,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, double?>>);

  @override
  _i4.Stream<_i5.Either<_i6.Failure, double>> subscribeToPriceStream(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPriceStream,
          [symbol],
        ),
        returnValue: _i4.Stream<_i5.Either<_i6.Failure, double>>.empty(),
      ) as _i4.Stream<_i5.Either<_i6.Failure, double>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, DateTime?>> getLastPriceUpdate(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastPriceUpdate,
          [symbol],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, DateTime?>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, DateTime?>>(
          this,
          Invocation.method(
            #getLastPriceUpdate,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, DateTime?>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> clearPriceCache(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearPriceCache,
          [symbol],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #clearPriceCache,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> clearAllPrices() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllPrices,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #clearAllPrices,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, Map<String, double>>> getPrices(
          List<String>? symbols) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrices,
          [symbols],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, Map<String, double>>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, Map<String, double>>>(
          this,
          Invocation.method(
            #getPrices,
            [symbols],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, Map<String, double>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i8.TickerInfo>> getTickerInfo(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTickerInfo,
          [symbol],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i8.TickerInfo>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, _i8.TickerInfo>>(
          this,
          Invocation.method(
            #getTickerInfo,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i8.TickerInfo>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> updatePrice(_i9.Price? price) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrice,
          [price],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
          this,
          Invocation.method(
            #updatePrice,
            [price],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);
}

/// A class which mocks [TradeEvaluatorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTradeEvaluatorService extends _i1.Mock
    implements _i10.TradeEvaluatorService {
  MockTradeEvaluatorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool shouldBuyInitial({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    required bool? warmupSatisfied,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldBuyInitial,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
            #warmupSatisfied: warmupSatisfied,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldBuyNonInitial({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldBuyNonInitial,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldBuyGuarded({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? allowInitialBuy = false,
    double? availableBalance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldBuyGuarded,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
            #allowInitialBuy: allowInitialBuy,
            #availableBalance: availableBalance,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldSell({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? inDustCooldown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldSell,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
            #inDustCooldown: inDustCooldown,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<bool> shouldSellWithFees({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? inDustCooldown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldSellWithFees,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
            #inDustCooldown: inDustCooldown,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  bool shouldDcaBuy({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? compareAgainstAverage = false,
    double? availableBalance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldDcaBuy,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
            #compareAgainstAverage: compareAgainstAverage,
            #availableBalance: availableBalance,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.TradingDecision? evaluateTradingDecisions({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? allowInitialBuy = false,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #evaluateTradingDecisions,
        [],
        {
          #currentPrice: currentPrice,
          #state: state,
          #settings: settings,
          #allowInitialBuy: allowInitialBuy,
        },
      )) as _i10.TradingDecision?);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i10.TradingDecision?>>
      evaluateTradingDecisionsWithFees({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
    bool? allowInitialBuy = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #evaluateTradingDecisionsWithFees,
              [],
              {
                #currentPrice: currentPrice,
                #state: state,
                #settings: settings,
                #allowInitialBuy: allowInitialBuy,
              },
            ),
            returnValue: _i4
                .Future<_i5.Either<_i6.Failure, _i10.TradingDecision?>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, _i10.TradingDecision?>>(
              this,
              Invocation.method(
                #evaluateTradingDecisionsWithFees,
                [],
                {
                  #currentPrice: currentPrice,
                  #state: state,
                  #settings: settings,
                  #allowInitialBuy: allowInitialBuy,
                },
              ),
            )),
          ) as _i4.Future<_i5.Either<_i6.Failure, _i10.TradingDecision?>>);

  @override
  _i2.AppStrategyState evaluateVolatilityAndUpdateState({
    required double? currentPrice,
    required _i2.AppStrategyState? state,
    required _i11.AppSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evaluateVolatilityAndUpdateState,
          [],
          {
            #currentPrice: currentPrice,
            #state: state,
            #settings: settings,
          },
        ),
        returnValue: _FakeAppStrategyState_0(
          this,
          Invocation.method(
            #evaluateVolatilityAndUpdateState,
            [],
            {
              #currentPrice: currentPrice,
              #state: state,
              #settings: settings,
            },
          ),
        ),
      ) as _i2.AppStrategyState);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i12.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> saveAccountInfo(
          _i13.AccountInfo? accountInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAccountInfo,
          [accountInfo],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #saveAccountInfo,
            [accountInfo],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo?>> getAccountInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo?>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, _i13.AccountInfo?>>(
          this,
          Invocation.method(
            #getAccountInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo?>>);

  @override
  _i4.Stream<_i5.Either<_i6.Failure, _i13.AccountInfo>>
      subscribeToAccountInfoStream() => (super.noSuchMethod(
            Invocation.method(
              #subscribeToAccountInfoStream,
              [],
            ),
            returnValue:
                _i4.Stream<_i5.Either<_i6.Failure, _i13.AccountInfo>>.empty(),
          ) as _i4.Stream<_i5.Either<_i6.Failure, _i13.AccountInfo>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> clearAccountInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAccountInfo,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #clearAccountInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo>> refreshAccountInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAccountInfo,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, _i13.AccountInfo>>(
          this,
          Invocation.method(
            #refreshAccountInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i13.AccountInfo>>);
}

/// A class which mocks [ISymbolInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISymbolInfoRepository extends _i1.Mock
    implements _i14.ISymbolInfoRepository {
  MockISymbolInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i15.SymbolInfo>> getSymbolInfo(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSymbolInfo,
          [symbol],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i15.SymbolInfo>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, _i15.SymbolInfo>>(
          this,
          Invocation.method(
            #getSymbolInfo,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i15.SymbolInfo>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>> refreshSymbolInfoCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSymbolInfoCache,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, _i5.Unit>>(
          this,
          Invocation.method(
            #refreshSymbolInfoCache,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i5.Unit>>);
}

/// A class which mocks [AtomicStateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicStateManager extends _i1.Mock
    implements _i16.AtomicStateManager {
  MockAtomicStateManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get persistChanges => (super.noSuchMethod(
        Invocation.getter(#persistChanges),
        returnValue: false,
      ) as bool);

  @override
  Duration get cacheTimeout => (super.noSuchMethod(
        Invocation.getter(#cacheTimeout),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#cacheTimeout),
        ),
      ) as Duration);

  @override
  int get maxCacheEntries => (super.noSuchMethod(
        Invocation.getter(#maxCacheEntries),
        returnValue: 0,
      ) as int);

  @override
  Duration get maxCacheAge => (super.noSuchMethod(
        Invocation.getter(#maxCacheAge),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#maxCacheAge),
        ),
      ) as Duration);

  @override
  _i4.Future<
      _i5.Either<_i6.Failure, _i2.AppStrategyState>> executeAtomicOperation(
    String? symbol,
    _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>> Function(
            _i2.AppStrategyState)?
        operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeAtomicOperation,
          [
            symbol,
            operation,
          ],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, _i2.AppStrategyState>>(
          this,
          Invocation.method(
            #executeAtomicOperation,
            [
              symbol,
              operation,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateCacheForSymbol(String? symbol) => super.noSuchMethod(
        Invocation.method(
          #invalidateCacheForSymbol,
          [symbol],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void forceCacheCleanup() => super.noSuchMethod(
        Invocation.method(
          #forceCacheCleanup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startPeriodicCleanup(
          {Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(
          #startPeriodicCleanup,
          [],
          {#interval: interval},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPeriodicCleanup() => super.noSuchMethod(
        Invocation.method(
          #stopPeriodicCleanup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> performHeartbeat() => (super.noSuchMethod(
        Invocation.method(
          #performHeartbeat,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>> getState(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getState,
          [symbol],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>>.value(
                _i7.dummyValue<_i5.Either<_i6.Failure, _i2.AppStrategyState>>(
          this,
          Invocation.method(
            #getState,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i2.AppStrategyState>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> forceUpdateState(
          _i2.AppStrategyState? state) =>
      (super.noSuchMethod(
        Invocation.method(
          #forceUpdateState,
          [state],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #forceUpdateState,
            [state],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  void seedState(_i2.AppStrategyState? state) => super.noSuchMethod(
        Invocation.method(
          #seedState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
