// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/account_info_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/app_settings_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/app_strategy_state_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/app_trade_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/balance_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/fifo_app_trade_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/log_settings_hive_dto.dart';
import 'package:neotradingbotback1777/infrastructure/persistence/hive/dtos/symbol_info_hive_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountInfoHiveDtoAdapter());
    registerAdapter(AppSettingsHiveDtoAdapter());
    registerAdapter(AppStrategyStateHiveDtoAdapter());
    registerAdapter(AppTradeHiveDtoAdapter());
    registerAdapter(BalanceHiveDtoAdapter());
    registerAdapter(FifoAppTradeHiveDtoAdapter());
    registerAdapter(LogSettingsHiveDtoAdapter());
    registerAdapter(SymbolInfoHiveDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountInfoHiveDtoAdapter());
    registerAdapter(AppSettingsHiveDtoAdapter());
    registerAdapter(AppStrategyStateHiveDtoAdapter());
    registerAdapter(AppTradeHiveDtoAdapter());
    registerAdapter(BalanceHiveDtoAdapter());
    registerAdapter(FifoAppTradeHiveDtoAdapter());
    registerAdapter(LogSettingsHiveDtoAdapter());
    registerAdapter(SymbolInfoHiveDtoAdapter());
  }
}
