// Mocks generated by Mockito 5.4.6 from annotations
// in neotradingbotback1777/test/application/managers/atomic_state_manager_race_condition_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:neotradingbotback1777/domain/entities/app_strategy_state.dart'
    as _i6;
import 'package:neotradingbotback1777/domain/failures/failures.dart' as _i5;
import 'package:neotradingbotback1777/domain/repositories/strategy_state_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StrategyStateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrategyStateRepository extends _i1.Mock
    implements _i2.StrategyStateRepository {
  MockStrategyStateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> saveStrategyState(
          _i6.AppStrategyState? state) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStrategyState,
          [state],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #saveStrategyState,
            [state],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.AppStrategyState?>> getStrategyState(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStrategyState,
          [symbol],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.AppStrategyState?>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.AppStrategyState?>>(
          this,
          Invocation.method(
            #getStrategyState,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.AppStrategyState?>>);

  @override
  _i3.Stream<
      _i4.Either<_i5.Failure, _i6.AppStrategyState>> subscribeToStateStream(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToStateStream,
          [symbol],
        ),
        returnValue:
            _i3.Stream<_i4.Either<_i5.Failure, _i6.AppStrategyState>>.empty(),
      ) as _i3.Stream<_i4.Either<_i5.Failure, _i6.AppStrategyState>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.AppStrategyState>>
      updateStrategyStateAtomically(
    String? symbol,
    _i6.AppStrategyState Function(_i6.AppStrategyState?)? updateFunction,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateStrategyStateAtomically,
              [
                symbol,
                updateFunction,
              ],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, _i6.AppStrategyState>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.AppStrategyState>>(
              this,
              Invocation.method(
                #updateStrategyStateAtomically,
                [
                  symbol,
                  updateFunction,
                ],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, _i6.AppStrategyState>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> resetStrategyState(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetStrategyState,
          [symbol],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #resetStrategyState,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, Map<String, _i6.AppStrategyState>>>
      getAllStrategyStates() => (super.noSuchMethod(
            Invocation.method(
              #getAllStrategyStates,
              [],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    Map<String, _i6.AppStrategyState>>>.value(_i7.dummyValue<
                _i4.Either<_i5.Failure, Map<String, _i6.AppStrategyState>>>(
              this,
              Invocation.method(
                #getAllStrategyStates,
                [],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, Map<String, _i6.AppStrategyState>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteStrategyState(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStrategyState,
          [symbol],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteStrategyState,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> hasStrategyState(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasStrategyState,
          [symbol],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
          this,
          Invocation.method(
            #hasStrategyState,
            [symbol],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool>>);
}
